#**ANN – ARTIFICIAL NEURAL NETWORK :**

#**IMPORTANT LIBRARIES :**

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

**DATA UPLOADING :**

In [ ]:
Data = pd.read_csv('spam.csv', encoding='latin-1')

Data = Data.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)

**DATA TO DATA CONVERT :**

In [ ]:
df=Data

df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

**CHANGE THE COLUMNS NAME :**

In [ ]:
df.columns=['SPAM','MESSAGE']
df.head()

   SPAM                                            MESSAGE
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

**SHAPE :**

In [ ]:
df.shape

(5572, 2)

**COUNT :**

In [ ]:
df['SPAM'].value_counts()

SPAM
ham     4825
spam     747
Name: count, dtype: int64

**ENCODER :**

In [ ]:
encoder = LabelEncoder()

df["SPAM"]=encoder.fit_transform(df["SPAM"])

In [ ]:
df['SPAM'].value_counts()

SPAM
0    4825
1     747
Name: count, dtype: int64

In [ ]:
df.head(2)

   SPAM                                            MESSAGE
0     0  Go until jurong point, crazy.. Available only ...
1     0                      Ok lar... Joking wif u oni...

In [ ]:
X=df['MESSAGE']
y=df['SPAM']

In [ ]:
vec = TfidfVectorizer(max_features=5000)

X = vec.fit_transform(X).toarray()

**TRAIN TO TEST SPLIT :**

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

**SEQUENTIAL :**

In [ ]:
model = Sequential()

model.add(Dense(128, activation='relu', input_shape=(5000,)))   # 1ST HIDDEN LAYER WITH 128 NODES    -   LEARN BASIC PATTERN        - RELU IS ACTIVATION FUNCTION
model.add(Dense(64, activation='relu'))                         # 2ND HIDDEN LAYER WITH 64 NODES     -   LEARNS MEANING FULL PATTERN
model.add(Dense(1, activation='sigmoid'))                       # 3RD HINDEN LAYER OR OUTPUT LAYER   -   BINARY OUTPUT [1],[0]      - SIGMOID IS OUTPUT FUNCTION

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

**MODEL TRAIN :**

In [ ]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",         #  0 | 1  to calculate how much loss we get.
    metrics=["accuracy"]
)


model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_train,y_train))        #  epochs means - iteration

Epoch 1/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.8810 - loss: 0.4053 - val_accuracy: 0.9926 - val_loss: 0.0600
Epoch 2/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9926 - loss: 0.0418 - val_accuracy: 0.9980 - val_loss: 0.0104
Epoch 3/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.9982 - loss: 0.0074 - val_accuracy: 0.9993 - val_loss: 0.0028
Epoch 4/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9994 - loss: 0.0030 - val_accuracy: 0.9998 - val_loss: 0.0013
Epoch 5/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.9998 - loss: 0.0010 - val_accuracy: 1.0000 - val_loss: 5.4465e-04
Epoch 6/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 8s 57ms/step - accuracy: 1.0000 - loss: 4.8614e-04 - val_accuracy: 1.0000 - val_loss: 3.1704e-04
Epoch 7/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 10s 52ms/step - accuracy: 1.0000 - loss: 3.1359e-04 - val_accuracy: 1.0000 - val_loss: 2.1300e-04
Epoch 8/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - accuracy: 1.0000 - loss: 1.9130e-04 - val_accuracy: 1.0000 - val_loss: 1.5193e-04
Epoch 9/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - accuracy: 1.0000 - loss: 1.4441e-04 - val_accuracy: 1.0000 - val_loss: 1.1401e-04
Epoch 10/10
140/140 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - accuracy: 1.0000 - loss: 1.0407e-04 - val_accuracy: 1.0000 - val_loss: 8.7496e-05

**PREDICTION :**

In [ ]:
y_pred = model.predict(X_test)

35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step

In [ ]:
y_pred

array([[1.5522476e-04],
       [4.3806449e-06],
       [9.9900329e-01],
       ...,
       [3.5644624e-07],
       [3.2140958e-04],
       [9.9643618e-01]], dtype=float32)

In [ ]:
y_pred = (y_pred > 0.5).astype(int)

In [ ]:
y_pred

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [1]])

**ACCURACY :**

In [ ]:
print("ACC = ",accuracy_score(y_test,y_pred))

ACC =  0.97847533632287

**EXPLAIN WITH LOOP CONDITION**

In [ ]:
while True:
  sample = []
  sample = str(input("ENTER YOUR MAIL : "))
  if sample.lower() == 'end':
    break
  sam_vec = vec.transform([sample]).toarray()
  res = model.predict(sam_vec)


  if res < 0.5 :
    print("\n\nGOOD EMAIL\n\n")
  else:
    print("\n\nSPAM EMAIL\n\n")

ENTER YOUR MAIL : Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


GOOD EMAIL


ENTER YOUR MAIL : Ok lar... Joking wif u oni...
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


GOOD EMAIL


ENTER YOUR MAIL : Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


SPAM EMAIL


ENTER YOUR MAIL : Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


SPAM EMAIL


ENTER YOUR MAIL : end